// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scrabble.Models;

namespace Scrabble.Migrations
{
    [DbContext(typeof(ScrabbleContext))]
    [Migration("20190424030410_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scrabble.Models.Board", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Columns");

                    b.Property<int>("GameID");

                    b.Property<int>("Rows");

                    b.HasKey("ID");

                    b.HasIndex("GameID")
                        .IsUnique();

                    b.ToTable("Boards");

                    b.HasData(
                        new { ID = 1, Columns = 15, GameID = 1, Rows = 15 },
                        new { ID = 2, Columns = 15, GameID = 2, Rows = 15 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.BoardTile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardID");

                    b.Property<int>("BoardLocationX");

                    b.Property<int>("BoardLocationY");

                    b.Property<int>("BoardTileTypeID");

                    b.Property<int?>("CharTileID");

                    b.Property<bool>("IsFilled");

                    b.HasKey("ID");

                    b.HasIndex("BoardID");

                    b.HasIndex("BoardTileTypeID");

                    b.HasIndex("CharTileID");

                    b.ToTable("BoardTiles");

                    b.HasData(
                        new { ID = 1, BoardID = 1, BoardLocationX = 0, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 2, BoardID = 1, BoardLocationX = 1, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 3, BoardID = 1, BoardLocationX = 2, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 4, BoardID = 1, BoardLocationX = 3, BoardLocationY = 0, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 5, BoardID = 1, BoardLocationX = 4, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 6, BoardID = 1, BoardLocationX = 5, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 7, BoardID = 1, BoardLocationX = 6, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 8, BoardID = 1, BoardLocationX = 7, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 9, BoardID = 1, BoardLocationX = 8, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 10, BoardID = 1, BoardLocationX = 9, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 11, BoardID = 1, BoardLocationX = 10, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 12, BoardID = 1, BoardLocationX = 11, BoardLocationY = 0, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 13, BoardID = 1, BoardLocationX = 12, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 14, BoardID = 1, BoardLocationX = 13, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 15, BoardID = 1, BoardLocationX = 14, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 16, BoardID = 1, BoardLocationX = 0, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 17, BoardID = 1, BoardLocationX = 1, BoardLocationY = 1, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 18, BoardID = 1, BoardLocationX = 2, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 19, BoardID = 1, BoardLocationX = 3, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 20, BoardID = 1, BoardLocationX = 4, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 21, BoardID = 1, BoardLocationX = 5, BoardLocationY = 1, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 22, BoardID = 1, BoardLocationX = 6, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 23, BoardID = 1, BoardLocationX = 7, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 24, BoardID = 1, BoardLocationX = 8, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 25, BoardID = 1, BoardLocationX = 9, BoardLocationY = 1, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 26, BoardID = 1, BoardLocationX = 10, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 27, BoardID = 1, BoardLocationX = 11, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 28, BoardID = 1, BoardLocationX = 12, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 29, BoardID = 1, BoardLocationX = 13, BoardLocationY = 1, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 30, BoardID = 1, BoardLocationX = 14, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 31, BoardID = 1, BoardLocationX = 0, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 32, BoardID = 1, BoardLocationX = 1, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 33, BoardID = 1, BoardLocationX = 2, BoardLocationY = 2, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 34, BoardID = 1, BoardLocationX = 3, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 35, BoardID = 1, BoardLocationX = 4, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 36, BoardID = 1, BoardLocationX = 5, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 37, BoardID = 1, BoardLocationX = 6, BoardLocationY = 2, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 38, BoardID = 1, BoardLocationX = 7, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 39, BoardID = 1, BoardLocationX = 8, BoardLocationY = 2, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 40, BoardID = 1, BoardLocationX = 9, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 41, BoardID = 1, BoardLocationX = 10, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 42, BoardID = 1, BoardLocationX = 11, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 43, BoardID = 1, BoardLocationX = 12, BoardLocationY = 2, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 44, BoardID = 1, BoardLocationX = 13, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 45, BoardID = 1, BoardLocationX = 14, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 46, BoardID = 1, BoardLocationX = 0, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 47, BoardID = 1, BoardLocationX = 1, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 48, BoardID = 1, BoardLocationX = 2, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 49, BoardID = 1, BoardLocationX = 3, BoardLocationY = 3, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 50, BoardID = 1, BoardLocationX = 4, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 51, BoardID = 1, BoardLocationX = 5, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 52, BoardID = 1, BoardLocationX = 6, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 53, BoardID = 1, BoardLocationX = 7, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 54, BoardID = 1, BoardLocationX = 8, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 55, BoardID = 1, BoardLocationX = 9, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 56, BoardID = 1, BoardLocationX = 10, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 57, BoardID = 1, BoardLocationX = 11, BoardLocationY = 3, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 58, BoardID = 1, BoardLocationX = 12, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 59, BoardID = 1, BoardLocationX = 13, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 60, BoardID = 1, BoardLocationX = 14, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 61, BoardID = 1, BoardLocationX = 0, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 62, BoardID = 1, BoardLocationX = 1, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 63, BoardID = 1, BoardLocationX = 2, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 64, BoardID = 1, BoardLocationX = 3, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 65, BoardID = 1, BoardLocationX = 4, BoardLocationY = 4, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 66, BoardID = 1, BoardLocationX = 5, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 67, BoardID = 1, BoardLocationX = 6, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 68, BoardID = 1, BoardLocationX = 7, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 69, BoardID = 1, BoardLocationX = 8, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 70, BoardID = 1, BoardLocationX = 9, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 71, BoardID = 1, BoardLocationX = 10, BoardLocationY = 4, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 72, BoardID = 1, BoardLocationX = 11, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 73, BoardID = 1, BoardLocationX = 12, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 74, BoardID = 1, BoardLocationX = 13, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 75, BoardID = 1, BoardLocationX = 14, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 76, BoardID = 1, BoardLocationX = 0, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 77, BoardID = 1, BoardLocationX = 1, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 78, BoardID = 1, BoardLocationX = 2, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 79, BoardID = 1, BoardLocationX = 3, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 80, BoardID = 1, BoardLocationX = 4, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 81, BoardID = 1, BoardLocationX = 5, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 82, BoardID = 1, BoardLocationX = 6, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 83, BoardID = 1, BoardLocationX = 7, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 84, BoardID = 1, BoardLocationX = 8, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 85, BoardID = 1, BoardLocationX = 9, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 86, BoardID = 1, BoardLocationX = 10, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 87, BoardID = 1, BoardLocationX = 11, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 88, BoardID = 1, BoardLocationX = 12, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 89, BoardID = 1, BoardLocationX = 13, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 90, BoardID = 1, BoardLocationX = 14, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 91, BoardID = 1, BoardLocationX = 0, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 92, BoardID = 1, BoardLocationX = 1, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 93, BoardID = 1, BoardLocationX = 2, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 94, BoardID = 1, BoardLocationX = 3, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 95, BoardID = 1, BoardLocationX = 4, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 96, BoardID = 1, BoardLocationX = 5, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 97, BoardID = 1, BoardLocationX = 6, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 98, BoardID = 1, BoardLocationX = 7, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 99, BoardID = 1, BoardLocationX = 8, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 100, BoardID = 1, BoardLocationX = 9, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 101, BoardID = 1, BoardLocationX = 10, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 102, BoardID = 1, BoardLocationX = 11, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 103, BoardID = 1, BoardLocationX = 12, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 104, BoardID = 1, BoardLocationX = 13, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 105, BoardID = 1, BoardLocationX = 14, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 106, BoardID = 1, BoardLocationX = 0, BoardLocationY = 7, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 107, BoardID = 1, BoardLocationX = 1, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 108, BoardID = 1, BoardLocationX = 2, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 109, BoardID = 1, BoardLocationX = 3, BoardLocationY = 7, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 110, BoardID = 1, BoardLocationX = 4, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 111, BoardID = 1, BoardLocationX = 5, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 112, BoardID = 1, BoardLocationX = 6, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 113, BoardID = 1, BoardLocationX = 7, BoardLocationY = 7, BoardTileTypeID = 6, IsFilled = false },
                        new { ID = 114, BoardID = 1, BoardLocationX = 8, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 115, BoardID = 1, BoardLocationX = 9, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 116, BoardID = 1, BoardLocationX = 10, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 117, BoardID = 1, BoardLocationX = 11, BoardLocationY = 7, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 118, BoardID = 1, BoardLocationX = 12, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 119, BoardID = 1, BoardLocationX = 13, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 120, BoardID = 1, BoardLocationX = 14, BoardLocationY = 7, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 121, BoardID = 1, BoardLocationX = 0, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 122, BoardID = 1, BoardLocationX = 1, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 123, BoardID = 1, BoardLocationX = 2, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 124, BoardID = 1, BoardLocationX = 3, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 125, BoardID = 1, BoardLocationX = 4, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 126, BoardID = 1, BoardLocationX = 5, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 127, BoardID = 1, BoardLocationX = 6, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 128, BoardID = 1, BoardLocationX = 7, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 129, BoardID = 1, BoardLocationX = 8, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 130, BoardID = 1, BoardLocationX = 9, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 131, BoardID = 1, BoardLocationX = 10, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 132, BoardID = 1, BoardLocationX = 11, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 133, BoardID = 1, BoardLocationX = 12, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 134, BoardID = 1, BoardLocationX = 13, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 135, BoardID = 1, BoardLocationX = 14, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 136, BoardID = 1, BoardLocationX = 0, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 137, BoardID = 1, BoardLocationX = 1, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 138, BoardID = 1, BoardLocationX = 2, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 139, BoardID = 1, BoardLocationX = 3, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 140, BoardID = 1, BoardLocationX = 4, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 141, BoardID = 1, BoardLocationX = 5, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 142, BoardID = 1, BoardLocationX = 6, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 143, BoardID = 1, BoardLocationX = 7, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 144, BoardID = 1, BoardLocationX = 8, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 145, BoardID = 1, BoardLocationX = 9, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 146, BoardID = 1, BoardLocationX = 10, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 147, BoardID = 1, BoardLocationX = 11, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 148, BoardID = 1, BoardLocationX = 12, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 149, BoardID = 1, BoardLocationX = 13, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 150, BoardID = 1, BoardLocationX = 14, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 151, BoardID = 1, BoardLocationX = 0, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 152, BoardID = 1, BoardLocationX = 1, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 153, BoardID = 1, BoardLocationX = 2, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 154, BoardID = 1, BoardLocationX = 3, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 155, BoardID = 1, BoardLocationX = 4, BoardLocationY = 10, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 156, BoardID = 1, BoardLocationX = 5, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 157, BoardID = 1, BoardLocationX = 6, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 158, BoardID = 1, BoardLocationX = 7, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 159, BoardID = 1, BoardLocationX = 8, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 160, BoardID = 1, BoardLocationX = 9, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 161, BoardID = 1, BoardLocationX = 10, BoardLocationY = 10, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 162, BoardID = 1, BoardLocationX = 11, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 163, BoardID = 1, BoardLocationX = 12, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 164, BoardID = 1, BoardLocationX = 13, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 165, BoardID = 1, BoardLocationX = 14, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 166, BoardID = 1, BoardLocationX = 0, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 167, BoardID = 1, BoardLocationX = 1, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 168, BoardID = 1, BoardLocationX = 2, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 169, BoardID = 1, BoardLocationX = 3, BoardLocationY = 11, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 170, BoardID = 1, BoardLocationX = 4, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 171, BoardID = 1, BoardLocationX = 5, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 172, BoardID = 1, BoardLocationX = 6, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 173, BoardID = 1, BoardLocationX = 7, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 174, BoardID = 1, BoardLocationX = 8, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 175, BoardID = 1, BoardLocationX = 9, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 176, BoardID = 1, BoardLocationX = 10, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 177, BoardID = 1, BoardLocationX = 11, BoardLocationY = 11, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 178, BoardID = 1, BoardLocationX = 12, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 179, BoardID = 1, BoardLocationX = 13, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 180, BoardID = 1, BoardLocationX = 14, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 181, BoardID = 1, BoardLocationX = 0, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 182, BoardID = 1, BoardLocationX = 1, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 183, BoardID = 1, BoardLocationX = 2, BoardLocationY = 12, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 184, BoardID = 1, BoardLocationX = 3, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 185, BoardID = 1, BoardLocationX = 4, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 186, BoardID = 1, BoardLocationX = 5, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 187, BoardID = 1, BoardLocationX = 6, BoardLocationY = 12, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 188, BoardID = 1, BoardLocationX = 7, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 189, BoardID = 1, BoardLocationX = 8, BoardLocationY = 12, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 190, BoardID = 1, BoardLocationX = 9, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 191, BoardID = 1, BoardLocationX = 10, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 192, BoardID = 1, BoardLocationX = 11, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 193, BoardID = 1, BoardLocationX = 12, BoardLocationY = 12, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 194, BoardID = 1, BoardLocationX = 13, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 195, BoardID = 1, BoardLocationX = 14, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 196, BoardID = 1, BoardLocationX = 0, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 197, BoardID = 1, BoardLocationX = 1, BoardLocationY = 13, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 198, BoardID = 1, BoardLocationX = 2, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 199, BoardID = 1, BoardLocationX = 3, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 200, BoardID = 1, BoardLocationX = 4, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 201, BoardID = 1, BoardLocationX = 5, BoardLocationY = 13, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 202, BoardID = 1, BoardLocationX = 6, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 203, BoardID = 1, BoardLocationX = 7, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 204, BoardID = 1, BoardLocationX = 8, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 205, BoardID = 1, BoardLocationX = 9, BoardLocationY = 13, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 206, BoardID = 1, BoardLocationX = 10, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 207, BoardID = 1, BoardLocationX = 11, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 208, BoardID = 1, BoardLocationX = 12, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 209, BoardID = 1, BoardLocationX = 13, BoardLocationY = 13, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 210, BoardID = 1, BoardLocationX = 14, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 211, BoardID = 1, BoardLocationX = 0, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 212, BoardID = 1, BoardLocationX = 1, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 213, BoardID = 1, BoardLocationX = 2, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 214, BoardID = 1, BoardLocationX = 3, BoardLocationY = 14, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 215, BoardID = 1, BoardLocationX = 4, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 216, BoardID = 1, BoardLocationX = 5, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 217, BoardID = 1, BoardLocationX = 6, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 218, BoardID = 1, BoardLocationX = 7, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 219, BoardID = 1, BoardLocationX = 8, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 220, BoardID = 1, BoardLocationX = 9, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 221, BoardID = 1, BoardLocationX = 10, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 222, BoardID = 1, BoardLocationX = 11, BoardLocationY = 14, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 223, BoardID = 1, BoardLocationX = 12, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 224, BoardID = 1, BoardLocationX = 13, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 225, BoardID = 1, BoardLocationX = 14, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 226, BoardID = 2, BoardLocationX = 0, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 227, BoardID = 2, BoardLocationX = 1, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 228, BoardID = 2, BoardLocationX = 2, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 229, BoardID = 2, BoardLocationX = 3, BoardLocationY = 0, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 230, BoardID = 2, BoardLocationX = 4, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 231, BoardID = 2, BoardLocationX = 5, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 232, BoardID = 2, BoardLocationX = 6, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 233, BoardID = 2, BoardLocationX = 7, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 234, BoardID = 2, BoardLocationX = 8, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 235, BoardID = 2, BoardLocationX = 9, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 236, BoardID = 2, BoardLocationX = 10, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 237, BoardID = 2, BoardLocationX = 11, BoardLocationY = 0, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 238, BoardID = 2, BoardLocationX = 12, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 239, BoardID = 2, BoardLocationX = 13, BoardLocationY = 0, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 240, BoardID = 2, BoardLocationX = 14, BoardLocationY = 0, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 241, BoardID = 2, BoardLocationX = 0, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 242, BoardID = 2, BoardLocationX = 1, BoardLocationY = 1, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 243, BoardID = 2, BoardLocationX = 2, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 244, BoardID = 2, BoardLocationX = 3, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 245, BoardID = 2, BoardLocationX = 4, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 246, BoardID = 2, BoardLocationX = 5, BoardLocationY = 1, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 247, BoardID = 2, BoardLocationX = 6, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 248, BoardID = 2, BoardLocationX = 7, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 249, BoardID = 2, BoardLocationX = 8, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 250, BoardID = 2, BoardLocationX = 9, BoardLocationY = 1, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 251, BoardID = 2, BoardLocationX = 10, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 252, BoardID = 2, BoardLocationX = 11, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 253, BoardID = 2, BoardLocationX = 12, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 254, BoardID = 2, BoardLocationX = 13, BoardLocationY = 1, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 255, BoardID = 2, BoardLocationX = 14, BoardLocationY = 1, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 256, BoardID = 2, BoardLocationX = 0, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 257, BoardID = 2, BoardLocationX = 1, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 258, BoardID = 2, BoardLocationX = 2, BoardLocationY = 2, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 259, BoardID = 2, BoardLocationX = 3, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 260, BoardID = 2, BoardLocationX = 4, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 261, BoardID = 2, BoardLocationX = 5, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 262, BoardID = 2, BoardLocationX = 6, BoardLocationY = 2, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 263, BoardID = 2, BoardLocationX = 7, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 264, BoardID = 2, BoardLocationX = 8, BoardLocationY = 2, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 265, BoardID = 2, BoardLocationX = 9, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 266, BoardID = 2, BoardLocationX = 10, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 267, BoardID = 2, BoardLocationX = 11, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 268, BoardID = 2, BoardLocationX = 12, BoardLocationY = 2, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 269, BoardID = 2, BoardLocationX = 13, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 270, BoardID = 2, BoardLocationX = 14, BoardLocationY = 2, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 271, BoardID = 2, BoardLocationX = 0, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 272, BoardID = 2, BoardLocationX = 1, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 273, BoardID = 2, BoardLocationX = 2, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 274, BoardID = 2, BoardLocationX = 3, BoardLocationY = 3, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 275, BoardID = 2, BoardLocationX = 4, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 276, BoardID = 2, BoardLocationX = 5, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 277, BoardID = 2, BoardLocationX = 6, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 278, BoardID = 2, BoardLocationX = 7, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 279, BoardID = 2, BoardLocationX = 8, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 280, BoardID = 2, BoardLocationX = 9, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 281, BoardID = 2, BoardLocationX = 10, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 282, BoardID = 2, BoardLocationX = 11, BoardLocationY = 3, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 283, BoardID = 2, BoardLocationX = 12, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 284, BoardID = 2, BoardLocationX = 13, BoardLocationY = 3, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 285, BoardID = 2, BoardLocationX = 14, BoardLocationY = 3, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 286, BoardID = 2, BoardLocationX = 0, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 287, BoardID = 2, BoardLocationX = 1, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 288, BoardID = 2, BoardLocationX = 2, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 289, BoardID = 2, BoardLocationX = 3, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 290, BoardID = 2, BoardLocationX = 4, BoardLocationY = 4, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 291, BoardID = 2, BoardLocationX = 5, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 292, BoardID = 2, BoardLocationX = 6, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 293, BoardID = 2, BoardLocationX = 7, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 294, BoardID = 2, BoardLocationX = 8, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 295, BoardID = 2, BoardLocationX = 9, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 296, BoardID = 2, BoardLocationX = 10, BoardLocationY = 4, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 297, BoardID = 2, BoardLocationX = 11, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 298, BoardID = 2, BoardLocationX = 12, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 299, BoardID = 2, BoardLocationX = 13, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 300, BoardID = 2, BoardLocationX = 14, BoardLocationY = 4, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 301, BoardID = 2, BoardLocationX = 0, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 302, BoardID = 2, BoardLocationX = 1, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 303, BoardID = 2, BoardLocationX = 2, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 304, BoardID = 2, BoardLocationX = 3, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 305, BoardID = 2, BoardLocationX = 4, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 306, BoardID = 2, BoardLocationX = 5, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 307, BoardID = 2, BoardLocationX = 6, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 308, BoardID = 2, BoardLocationX = 7, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 309, BoardID = 2, BoardLocationX = 8, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 310, BoardID = 2, BoardLocationX = 9, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 311, BoardID = 2, BoardLocationX = 10, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 312, BoardID = 2, BoardLocationX = 11, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 313, BoardID = 2, BoardLocationX = 12, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 314, BoardID = 2, BoardLocationX = 13, BoardLocationY = 5, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 315, BoardID = 2, BoardLocationX = 14, BoardLocationY = 5, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 316, BoardID = 2, BoardLocationX = 0, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 317, BoardID = 2, BoardLocationX = 1, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 318, BoardID = 2, BoardLocationX = 2, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 319, BoardID = 2, BoardLocationX = 3, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 320, BoardID = 2, BoardLocationX = 4, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 321, BoardID = 2, BoardLocationX = 5, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 322, BoardID = 2, BoardLocationX = 6, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 323, BoardID = 2, BoardLocationX = 7, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 324, BoardID = 2, BoardLocationX = 8, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 325, BoardID = 2, BoardLocationX = 9, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 326, BoardID = 2, BoardLocationX = 10, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 327, BoardID = 2, BoardLocationX = 11, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 328, BoardID = 2, BoardLocationX = 12, BoardLocationY = 6, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 329, BoardID = 2, BoardLocationX = 13, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 330, BoardID = 2, BoardLocationX = 14, BoardLocationY = 6, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 331, BoardID = 2, BoardLocationX = 0, BoardLocationY = 7, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 332, BoardID = 2, BoardLocationX = 1, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 333, BoardID = 2, BoardLocationX = 2, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 334, BoardID = 2, BoardLocationX = 3, BoardLocationY = 7, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 335, BoardID = 2, BoardLocationX = 4, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 336, BoardID = 2, BoardLocationX = 5, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 337, BoardID = 2, BoardLocationX = 6, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 338, BoardID = 2, BoardLocationX = 7, BoardLocationY = 7, BoardTileTypeID = 6, IsFilled = false },
                        new { ID = 339, BoardID = 2, BoardLocationX = 8, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 340, BoardID = 2, BoardLocationX = 9, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 341, BoardID = 2, BoardLocationX = 10, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 342, BoardID = 2, BoardLocationX = 11, BoardLocationY = 7, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 343, BoardID = 2, BoardLocationX = 12, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 344, BoardID = 2, BoardLocationX = 13, BoardLocationY = 7, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 345, BoardID = 2, BoardLocationX = 14, BoardLocationY = 7, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 346, BoardID = 2, BoardLocationX = 0, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 347, BoardID = 2, BoardLocationX = 1, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 348, BoardID = 2, BoardLocationX = 2, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 349, BoardID = 2, BoardLocationX = 3, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 350, BoardID = 2, BoardLocationX = 4, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 351, BoardID = 2, BoardLocationX = 5, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 352, BoardID = 2, BoardLocationX = 6, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 353, BoardID = 2, BoardLocationX = 7, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 354, BoardID = 2, BoardLocationX = 8, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 355, BoardID = 2, BoardLocationX = 9, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 356, BoardID = 2, BoardLocationX = 10, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 357, BoardID = 2, BoardLocationX = 11, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 358, BoardID = 2, BoardLocationX = 12, BoardLocationY = 8, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 359, BoardID = 2, BoardLocationX = 13, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 360, BoardID = 2, BoardLocationX = 14, BoardLocationY = 8, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 361, BoardID = 2, BoardLocationX = 0, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 362, BoardID = 2, BoardLocationX = 1, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 363, BoardID = 2, BoardLocationX = 2, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 364, BoardID = 2, BoardLocationX = 3, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 365, BoardID = 2, BoardLocationX = 4, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 366, BoardID = 2, BoardLocationX = 5, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 367, BoardID = 2, BoardLocationX = 6, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 368, BoardID = 2, BoardLocationX = 7, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 369, BoardID = 2, BoardLocationX = 8, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 370, BoardID = 2, BoardLocationX = 9, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 371, BoardID = 2, BoardLocationX = 10, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 372, BoardID = 2, BoardLocationX = 11, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 373, BoardID = 2, BoardLocationX = 12, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 374, BoardID = 2, BoardLocationX = 13, BoardLocationY = 9, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 375, BoardID = 2, BoardLocationX = 14, BoardLocationY = 9, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 376, BoardID = 2, BoardLocationX = 0, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 377, BoardID = 2, BoardLocationX = 1, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 378, BoardID = 2, BoardLocationX = 2, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 379, BoardID = 2, BoardLocationX = 3, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 380, BoardID = 2, BoardLocationX = 4, BoardLocationY = 10, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 381, BoardID = 2, BoardLocationX = 5, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 382, BoardID = 2, BoardLocationX = 6, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 383, BoardID = 2, BoardLocationX = 7, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 384, BoardID = 2, BoardLocationX = 8, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 385, BoardID = 2, BoardLocationX = 9, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 386, BoardID = 2, BoardLocationX = 10, BoardLocationY = 10, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 387, BoardID = 2, BoardLocationX = 11, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 388, BoardID = 2, BoardLocationX = 12, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 389, BoardID = 2, BoardLocationX = 13, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 390, BoardID = 2, BoardLocationX = 14, BoardLocationY = 10, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 391, BoardID = 2, BoardLocationX = 0, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 392, BoardID = 2, BoardLocationX = 1, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 393, BoardID = 2, BoardLocationX = 2, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 394, BoardID = 2, BoardLocationX = 3, BoardLocationY = 11, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 395, BoardID = 2, BoardLocationX = 4, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 396, BoardID = 2, BoardLocationX = 5, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 397, BoardID = 2, BoardLocationX = 6, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 398, BoardID = 2, BoardLocationX = 7, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 399, BoardID = 2, BoardLocationX = 8, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 400, BoardID = 2, BoardLocationX = 9, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 401, BoardID = 2, BoardLocationX = 10, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 402, BoardID = 2, BoardLocationX = 11, BoardLocationY = 11, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 403, BoardID = 2, BoardLocationX = 12, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 404, BoardID = 2, BoardLocationX = 13, BoardLocationY = 11, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 405, BoardID = 2, BoardLocationX = 14, BoardLocationY = 11, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 406, BoardID = 2, BoardLocationX = 0, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 407, BoardID = 2, BoardLocationX = 1, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 408, BoardID = 2, BoardLocationX = 2, BoardLocationY = 12, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 409, BoardID = 2, BoardLocationX = 3, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 410, BoardID = 2, BoardLocationX = 4, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 411, BoardID = 2, BoardLocationX = 5, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 412, BoardID = 2, BoardLocationX = 6, BoardLocationY = 12, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 413, BoardID = 2, BoardLocationX = 7, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 414, BoardID = 2, BoardLocationX = 8, BoardLocationY = 12, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 415, BoardID = 2, BoardLocationX = 9, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 416, BoardID = 2, BoardLocationX = 10, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 417, BoardID = 2, BoardLocationX = 11, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 418, BoardID = 2, BoardLocationX = 12, BoardLocationY = 12, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 419, BoardID = 2, BoardLocationX = 13, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 420, BoardID = 2, BoardLocationX = 14, BoardLocationY = 12, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 421, BoardID = 2, BoardLocationX = 0, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 422, BoardID = 2, BoardLocationX = 1, BoardLocationY = 13, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 423, BoardID = 2, BoardLocationX = 2, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 424, BoardID = 2, BoardLocationX = 3, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 425, BoardID = 2, BoardLocationX = 4, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 426, BoardID = 2, BoardLocationX = 5, BoardLocationY = 13, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 427, BoardID = 2, BoardLocationX = 6, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 428, BoardID = 2, BoardLocationX = 7, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 429, BoardID = 2, BoardLocationX = 8, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 430, BoardID = 2, BoardLocationX = 9, BoardLocationY = 13, BoardTileTypeID = 3, IsFilled = false },
                        new { ID = 431, BoardID = 2, BoardLocationX = 10, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 432, BoardID = 2, BoardLocationX = 11, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 433, BoardID = 2, BoardLocationX = 12, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 434, BoardID = 2, BoardLocationX = 13, BoardLocationY = 13, BoardTileTypeID = 4, IsFilled = false },
                        new { ID = 435, BoardID = 2, BoardLocationX = 14, BoardLocationY = 13, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 436, BoardID = 2, BoardLocationX = 0, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 437, BoardID = 2, BoardLocationX = 1, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 438, BoardID = 2, BoardLocationX = 2, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 439, BoardID = 2, BoardLocationX = 3, BoardLocationY = 14, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 440, BoardID = 2, BoardLocationX = 4, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 441, BoardID = 2, BoardLocationX = 5, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 442, BoardID = 2, BoardLocationX = 6, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 443, BoardID = 2, BoardLocationX = 7, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false },
                        new { ID = 444, BoardID = 2, BoardLocationX = 8, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 445, BoardID = 2, BoardLocationX = 9, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 446, BoardID = 2, BoardLocationX = 10, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 447, BoardID = 2, BoardLocationX = 11, BoardLocationY = 14, BoardTileTypeID = 2, IsFilled = false },
                        new { ID = 448, BoardID = 2, BoardLocationX = 12, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 449, BoardID = 2, BoardLocationX = 13, BoardLocationY = 14, BoardTileTypeID = 1, IsFilled = false },
                        new { ID = 450, BoardID = 2, BoardLocationX = 14, BoardLocationY = 14, BoardTileTypeID = 5, IsFilled = false }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.BoardTileType", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("BoardTileTypes");

                    b.HasData(
                        new { ID = 1, Type = "Normal" },
                        new { ID = 2, Type = "Double_Letter" },
                        new { ID = 3, Type = "Triple_Letter" },
                        new { ID = 4, Type = "Double_Word" },
                        new { ID = 5, Type = "Triple_Word" },
                        new { ID = 6, Type = "Start" }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.BotType", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("BotTypes");

                    b.HasData(
                        new { ID = 1, Type = "High_Scorer" },
                        new { ID = 2, Type = "Rack_Balancer" }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.CharTile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameLanguageID");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("Score");

                    b.Property<int>("WordDictionaryID");

                    b.HasKey("ID");

                    b.HasIndex("GameLanguageID");

                    b.HasIndex("WordDictionaryID");

                    b.ToTable("CharTiles");

                    b.HasData(
                        new { ID = 1, GameLanguageID = 1, Letter = "*", Score = 0, WordDictionaryID = 1 },
                        new { ID = 2, GameLanguageID = 1, Letter = "A", Score = 1, WordDictionaryID = 1 },
                        new { ID = 3, GameLanguageID = 1, Letter = "B", Score = 3, WordDictionaryID = 1 },
                        new { ID = 4, GameLanguageID = 1, Letter = "C", Score = 3, WordDictionaryID = 1 },
                        new { ID = 5, GameLanguageID = 1, Letter = "D", Score = 2, WordDictionaryID = 1 },
                        new { ID = 6, GameLanguageID = 1, Letter = "E", Score = 1, WordDictionaryID = 1 },
                        new { ID = 7, GameLanguageID = 1, Letter = "F", Score = 4, WordDictionaryID = 1 },
                        new { ID = 8, GameLanguageID = 1, Letter = "G", Score = 2, WordDictionaryID = 1 },
                        new { ID = 9, GameLanguageID = 1, Letter = "H", Score = 4, WordDictionaryID = 1 },
                        new { ID = 10, GameLanguageID = 1, Letter = "I", Score = 1, WordDictionaryID = 1 },
                        new { ID = 11, GameLanguageID = 1, Letter = "J", Score = 8, WordDictionaryID = 1 },
                        new { ID = 12, GameLanguageID = 1, Letter = "K", Score = 5, WordDictionaryID = 1 },
                        new { ID = 13, GameLanguageID = 1, Letter = "L", Score = 1, WordDictionaryID = 1 },
                        new { ID = 14, GameLanguageID = 1, Letter = "M", Score = 3, WordDictionaryID = 1 },
                        new { ID = 15, GameLanguageID = 1, Letter = "N", Score = 1, WordDictionaryID = 1 },
                        new { ID = 16, GameLanguageID = 1, Letter = "O", Score = 1, WordDictionaryID = 1 },
                        new { ID = 17, GameLanguageID = 1, Letter = "P", Score = 3, WordDictionaryID = 1 },
                        new { ID = 18, GameLanguageID = 1, Letter = "Q", Score = 10, WordDictionaryID = 1 },
                        new { ID = 19, GameLanguageID = 1, Letter = "R", Score = 1, WordDictionaryID = 1 },
                        new { ID = 20, GameLanguageID = 1, Letter = "S", Score = 1, WordDictionaryID = 1 },
                        new { ID = 21, GameLanguageID = 1, Letter = "T", Score = 1, WordDictionaryID = 1 },
                        new { ID = 22, GameLanguageID = 1, Letter = "U", Score = 1, WordDictionaryID = 1 },
                        new { ID = 23, GameLanguageID = 1, Letter = "V", Score = 4, WordDictionaryID = 1 },
                        new { ID = 24, GameLanguageID = 1, Letter = "W", Score = 4, WordDictionaryID = 1 },
                        new { ID = 25, GameLanguageID = 1, Letter = "X", Score = 8, WordDictionaryID = 1 },
                        new { ID = 26, GameLanguageID = 1, Letter = "Y", Score = 4, WordDictionaryID = 1 },
                        new { ID = 27, GameLanguageID = 1, Letter = "Z", Score = 10, WordDictionaryID = 1 },
                        new { ID = 28, GameLanguageID = 1, Letter = "A", Score = 0, WordDictionaryID = 1 },
                        new { ID = 29, GameLanguageID = 1, Letter = "B", Score = 0, WordDictionaryID = 1 },
                        new { ID = 30, GameLanguageID = 1, Letter = "C", Score = 0, WordDictionaryID = 1 },
                        new { ID = 31, GameLanguageID = 1, Letter = "D", Score = 0, WordDictionaryID = 1 },
                        new { ID = 32, GameLanguageID = 1, Letter = "E", Score = 0, WordDictionaryID = 1 },
                        new { ID = 33, GameLanguageID = 1, Letter = "F", Score = 0, WordDictionaryID = 1 },
                        new { ID = 34, GameLanguageID = 1, Letter = "G", Score = 0, WordDictionaryID = 1 },
                        new { ID = 35, GameLanguageID = 1, Letter = "H", Score = 0, WordDictionaryID = 1 },
                        new { ID = 36, GameLanguageID = 1, Letter = "I", Score = 0, WordDictionaryID = 1 },
                        new { ID = 37, GameLanguageID = 1, Letter = "J", Score = 0, WordDictionaryID = 1 },
                        new { ID = 38, GameLanguageID = 1, Letter = "K", Score = 0, WordDictionaryID = 1 },
                        new { ID = 39, GameLanguageID = 1, Letter = "L", Score = 0, WordDictionaryID = 1 },
                        new { ID = 40, GameLanguageID = 1, Letter = "M", Score = 0, WordDictionaryID = 1 },
                        new { ID = 41, GameLanguageID = 1, Letter = "N", Score = 0, WordDictionaryID = 1 },
                        new { ID = 42, GameLanguageID = 1, Letter = "O", Score = 0, WordDictionaryID = 1 },
                        new { ID = 43, GameLanguageID = 1, Letter = "P", Score = 0, WordDictionaryID = 1 },
                        new { ID = 44, GameLanguageID = 1, Letter = "Q", Score = 0, WordDictionaryID = 1 },
                        new { ID = 45, GameLanguageID = 1, Letter = "R", Score = 0, WordDictionaryID = 1 },
                        new { ID = 46, GameLanguageID = 1, Letter = "S", Score = 0, WordDictionaryID = 1 },
                        new { ID = 47, GameLanguageID = 1, Letter = "T", Score = 0, WordDictionaryID = 1 },
                        new { ID = 48, GameLanguageID = 1, Letter = "U", Score = 0, WordDictionaryID = 1 },
                        new { ID = 49, GameLanguageID = 1, Letter = "V", Score = 0, WordDictionaryID = 1 },
                        new { ID = 50, GameLanguageID = 1, Letter = "W", Score = 0, WordDictionaryID = 1 },
                        new { ID = 51, GameLanguageID = 1, Letter = "X", Score = 0, WordDictionaryID = 1 },
                        new { ID = 52, GameLanguageID = 1, Letter = "Y", Score = 0, WordDictionaryID = 1 },
                        new { ID = 53, GameLanguageID = 1, Letter = "Z", Score = 0, WordDictionaryID = 1 },
                        new { ID = 54, GameLanguageID = 2, Letter = "*", Score = 0, WordDictionaryID = 2 },
                        new { ID = 55, GameLanguageID = 2, Letter = "А", Score = 1, WordDictionaryID = 2 },
                        new { ID = 56, GameLanguageID = 2, Letter = "Б", Score = 2, WordDictionaryID = 2 },
                        new { ID = 57, GameLanguageID = 2, Letter = "В", Score = 2, WordDictionaryID = 2 },
                        new { ID = 58, GameLanguageID = 2, Letter = "Г", Score = 3, WordDictionaryID = 2 },
                        new { ID = 59, GameLanguageID = 2, Letter = "Д", Score = 2, WordDictionaryID = 2 },
                        new { ID = 60, GameLanguageID = 2, Letter = "Е", Score = 1, WordDictionaryID = 2 },
                        new { ID = 61, GameLanguageID = 2, Letter = "Ж", Score = 4, WordDictionaryID = 2 },
                        new { ID = 62, GameLanguageID = 2, Letter = "З", Score = 4, WordDictionaryID = 2 },
                        new { ID = 63, GameLanguageID = 2, Letter = "И", Score = 1, WordDictionaryID = 2 },
                        new { ID = 64, GameLanguageID = 2, Letter = "Й", Score = 5, WordDictionaryID = 2 },
                        new { ID = 65, GameLanguageID = 2, Letter = "К", Score = 2, WordDictionaryID = 2 },
                        new { ID = 66, GameLanguageID = 2, Letter = "Л", Score = 2, WordDictionaryID = 2 },
                        new { ID = 67, GameLanguageID = 2, Letter = "М", Score = 2, WordDictionaryID = 2 },
                        new { ID = 68, GameLanguageID = 2, Letter = "Н", Score = 1, WordDictionaryID = 2 },
                        new { ID = 69, GameLanguageID = 2, Letter = "О", Score = 1, WordDictionaryID = 2 },
                        new { ID = 70, GameLanguageID = 2, Letter = "П", Score = 1, WordDictionaryID = 2 },
                        new { ID = 71, GameLanguageID = 2, Letter = "Р", Score = 1, WordDictionaryID = 2 },
                        new { ID = 72, GameLanguageID = 2, Letter = "С", Score = 1, WordDictionaryID = 2 },
                        new { ID = 73, GameLanguageID = 2, Letter = "Т", Score = 1, WordDictionaryID = 2 },
                        new { ID = 74, GameLanguageID = 2, Letter = "У", Score = 5, WordDictionaryID = 2 },
                        new { ID = 75, GameLanguageID = 2, Letter = "Ф", Score = 10, WordDictionaryID = 2 },
                        new { ID = 76, GameLanguageID = 2, Letter = "Х", Score = 5, WordDictionaryID = 2 },
                        new { ID = 77, GameLanguageID = 2, Letter = "Ц", Score = 8, WordDictionaryID = 2 },
                        new { ID = 78, GameLanguageID = 2, Letter = "Ч", Score = 5, WordDictionaryID = 2 },
                        new { ID = 79, GameLanguageID = 2, Letter = "Ш", Score = 8, WordDictionaryID = 2 },
                        new { ID = 80, GameLanguageID = 2, Letter = "Щ", Score = 10, WordDictionaryID = 2 },
                        new { ID = 81, GameLanguageID = 2, Letter = "Ъ", Score = 3, WordDictionaryID = 2 },
                        new { ID = 82, GameLanguageID = 2, Letter = "Ь", Score = 10, WordDictionaryID = 2 },
                        new { ID = 83, GameLanguageID = 2, Letter = "Ю", Score = 8, WordDictionaryID = 2 },
                        new { ID = 84, GameLanguageID = 2, Letter = "Я", Score = 5, WordDictionaryID = 2 },
                        new { ID = 85, GameLanguageID = 2, Letter = "А", Score = 0, WordDictionaryID = 2 },
                        new { ID = 86, GameLanguageID = 2, Letter = "Б", Score = 0, WordDictionaryID = 2 },
                        new { ID = 87, GameLanguageID = 2, Letter = "В", Score = 0, WordDictionaryID = 2 },
                        new { ID = 88, GameLanguageID = 2, Letter = "Г", Score = 0, WordDictionaryID = 2 },
                        new { ID = 89, GameLanguageID = 2, Letter = "Д", Score = 0, WordDictionaryID = 2 },
                        new { ID = 90, GameLanguageID = 2, Letter = "Е", Score = 0, WordDictionaryID = 2 },
                        new { ID = 91, GameLanguageID = 2, Letter = "Ж", Score = 0, WordDictionaryID = 2 },
                        new { ID = 92, GameLanguageID = 2, Letter = "З", Score = 0, WordDictionaryID = 2 },
                        new { ID = 93, GameLanguageID = 2, Letter = "И", Score = 0, WordDictionaryID = 2 },
                        new { ID = 94, GameLanguageID = 2, Letter = "Й", Score = 0, WordDictionaryID = 2 },
                        new { ID = 95, GameLanguageID = 2, Letter = "К", Score = 0, WordDictionaryID = 2 },
                        new { ID = 96, GameLanguageID = 2, Letter = "Л", Score = 0, WordDictionaryID = 2 },
                        new { ID = 97, GameLanguageID = 2, Letter = "М", Score = 0, WordDictionaryID = 2 },
                        new { ID = 98, GameLanguageID = 2, Letter = "Н", Score = 0, WordDictionaryID = 2 },
                        new { ID = 99, GameLanguageID = 2, Letter = "О", Score = 0, WordDictionaryID = 2 },
                        new { ID = 100, GameLanguageID = 2, Letter = "П", Score = 0, WordDictionaryID = 2 },
                        new { ID = 101, GameLanguageID = 2, Letter = "Р", Score = 0, WordDictionaryID = 2 },
                        new { ID = 102, GameLanguageID = 2, Letter = "С", Score = 0, WordDictionaryID = 2 },
                        new { ID = 103, GameLanguageID = 2, Letter = "Т", Score = 0, WordDictionaryID = 2 },
                        new { ID = 104, GameLanguageID = 2, Letter = "У", Score = 0, WordDictionaryID = 2 },
                        new { ID = 105, GameLanguageID = 2, Letter = "Ф", Score = 0, WordDictionaryID = 2 },
                        new { ID = 106, GameLanguageID = 2, Letter = "Х", Score = 0, WordDictionaryID = 2 },
                        new { ID = 107, GameLanguageID = 2, Letter = "Ц", Score = 0, WordDictionaryID = 2 },
                        new { ID = 108, GameLanguageID = 2, Letter = "Ч", Score = 0, WordDictionaryID = 2 },
                        new { ID = 109, GameLanguageID = 2, Letter = "Ш", Score = 0, WordDictionaryID = 2 },
                        new { ID = 110, GameLanguageID = 2, Letter = "Щ", Score = 0, WordDictionaryID = 2 },
                        new { ID = 111, GameLanguageID = 2, Letter = "Ъ", Score = 0, WordDictionaryID = 2 },
                        new { ID = 112, GameLanguageID = 2, Letter = "Ь", Score = 0, WordDictionaryID = 2 },
                        new { ID = 113, GameLanguageID = 2, Letter = "Ю", Score = 0, WordDictionaryID = 2 },
                        new { ID = 114, GameLanguageID = 2, Letter = "Я", Score = 0, WordDictionaryID = 2 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardID");

                    b.Property<int>("GameLanguageID");

                    b.Property<bool>("IsFinished");

                    b.Property<string>("Log");

                    b.Property<int>("PouchID");

                    b.Property<int>("WordDictionaryID");

                    b.HasKey("ID");

                    b.HasIndex("GameLanguageID");

                    b.HasIndex("WordDictionaryID");

                    b.ToTable("Games");

                    b.HasData(
                        new { ID = 1, BoardID = 1, GameLanguageID = 1, IsFinished = false, Log = "Enjoy the game!", PouchID = 1, WordDictionaryID = 1 },
                        new { ID = 2, BoardID = 2, GameLanguageID = 2, IsFinished = false, Log = "Enjoy the game!", PouchID = 2, WordDictionaryID = 2 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.GameLanguage", b =>
                {
                    b.Property<int>("ID");

                    b.Property<int>("CountOfLetters");

                    b.Property<string>("Language");

                    b.HasKey("ID");

                    b.ToTable("GameLanguages");

                    b.HasData(
                        new { ID = 1, CountOfLetters = 26, Language = "English" },
                        new { ID = 2, CountOfLetters = 30, Language = "Bulgarian" }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Move", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("End");

                    b.Property<int>("GameID");

                    b.Property<int>("Index");

                    b.Property<bool>("IsHorizontal");

                    b.Property<bool>("IsNew");

                    b.Property<int>("MoveNumber");

                    b.Property<int>("PlayerID");

                    b.Property<int>("Score");

                    b.Property<int>("Start");

                    b.Property<string>("Word");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Scrabble.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AtHand");

                    b.Property<int?>("BotTypeID");

                    b.Property<int>("GameID");

                    b.Property<bool>("IsHuman");

                    b.Property<string>("Name");

                    b.Property<int>("PouchID");

                    b.Property<int>("RackID");

                    b.Property<int>("Score");

                    b.Property<int>("SkipsOrRedrawsUsed");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PouchID");

                    b.ToTable("Players");

                    b.HasData(
                        new { ID = 1, AtHand = true, GameID = 1, IsHuman = true, Name = "Simeon", PouchID = 1, RackID = 1, Score = 0, SkipsOrRedrawsUsed = 0 },
                        new { ID = 2, AtHand = false, BotTypeID = 1, GameID = 1, IsHuman = false, Name = "High Scorer Bot", PouchID = 1, RackID = 2, Score = 0, SkipsOrRedrawsUsed = 0 },
                        new { ID = 3, AtHand = false, GameID = 1, IsHuman = true, Name = "Dobromir", PouchID = 1, RackID = 3, Score = 0, SkipsOrRedrawsUsed = 0 },
                        new { ID = 4, AtHand = false, BotTypeID = 2, GameID = 1, IsHuman = false, Name = "Rack Balancer Bot", PouchID = 1, RackID = 4, Score = 0, SkipsOrRedrawsUsed = 0 },
                        new { ID = 5, AtHand = true, GameID = 2, IsHuman = true, PouchID = 2, RackID = 5, Score = 0, SkipsOrRedrawsUsed = 0 },
                        new { ID = 6, AtHand = false, BotTypeID = 1, GameID = 2, IsHuman = false, Name = "High Scorer Bot", PouchID = 2, RackID = 6, Score = 0, SkipsOrRedrawsUsed = 0 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Pouch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameID");

                    b.HasKey("ID");

                    b.HasIndex("GameID")
                        .IsUnique();

                    b.ToTable("Pouches");

                    b.HasData(
                        new { ID = 1, GameID = 1 },
                        new { ID = 2, GameID = 2 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Pouch_CharTile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharTileID");

                    b.Property<int>("Count");

                    b.Property<int>("PouchID");

                    b.HasKey("ID");

                    b.HasIndex("CharTileID");

                    b.HasIndex("PouchID");

                    b.ToTable("Pouch_CharTiles");

                    b.HasData(
                        new { ID = 1, CharTileID = 1, Count = 0, PouchID = 1 },
                        new { ID = 2, CharTileID = 2, Count = 9, PouchID = 1 },
                        new { ID = 3, CharTileID = 3, Count = 2, PouchID = 1 },
                        new { ID = 4, CharTileID = 4, Count = 2, PouchID = 1 },
                        new { ID = 5, CharTileID = 5, Count = 4, PouchID = 1 },
                        new { ID = 6, CharTileID = 6, Count = 12, PouchID = 1 },
                        new { ID = 7, CharTileID = 7, Count = 2, PouchID = 1 },
                        new { ID = 8, CharTileID = 8, Count = 3, PouchID = 1 },
                        new { ID = 9, CharTileID = 9, Count = 2, PouchID = 1 },
                        new { ID = 10, CharTileID = 10, Count = 9, PouchID = 1 },
                        new { ID = 11, CharTileID = 11, Count = 1, PouchID = 1 },
                        new { ID = 12, CharTileID = 12, Count = 1, PouchID = 1 },
                        new { ID = 13, CharTileID = 13, Count = 4, PouchID = 1 },
                        new { ID = 14, CharTileID = 14, Count = 2, PouchID = 1 },
                        new { ID = 15, CharTileID = 15, Count = 6, PouchID = 1 },
                        new { ID = 16, CharTileID = 16, Count = 8, PouchID = 1 },
                        new { ID = 17, CharTileID = 17, Count = 2, PouchID = 1 },
                        new { ID = 18, CharTileID = 18, Count = 1, PouchID = 1 },
                        new { ID = 19, CharTileID = 19, Count = 6, PouchID = 1 },
                        new { ID = 20, CharTileID = 20, Count = 4, PouchID = 1 },
                        new { ID = 21, CharTileID = 21, Count = 6, PouchID = 1 },
                        new { ID = 22, CharTileID = 22, Count = 4, PouchID = 1 },
                        new { ID = 23, CharTileID = 23, Count = 2, PouchID = 1 },
                        new { ID = 24, CharTileID = 24, Count = 2, PouchID = 1 },
                        new { ID = 25, CharTileID = 25, Count = 1, PouchID = 1 },
                        new { ID = 26, CharTileID = 26, Count = 2, PouchID = 1 },
                        new { ID = 27, CharTileID = 27, Count = 1, PouchID = 1 },
                        new { ID = 54, CharTileID = 54, Count = 0, PouchID = 2 },
                        new { ID = 55, CharTileID = 55, Count = 12, PouchID = 2 },
                        new { ID = 56, CharTileID = 56, Count = 3, PouchID = 2 },
                        new { ID = 57, CharTileID = 57, Count = 4, PouchID = 2 },
                        new { ID = 58, CharTileID = 58, Count = 3, PouchID = 2 },
                        new { ID = 59, CharTileID = 59, Count = 2, PouchID = 2 },
                        new { ID = 60, CharTileID = 60, Count = 8, PouchID = 2 },
                        new { ID = 61, CharTileID = 61, Count = 2, PouchID = 2 },
                        new { ID = 62, CharTileID = 62, Count = 2, PouchID = 2 },
                        new { ID = 63, CharTileID = 63, Count = 8, PouchID = 2 },
                        new { ID = 64, CharTileID = 64, Count = 1, PouchID = 2 },
                        new { ID = 65, CharTileID = 65, Count = 3, PouchID = 2 },
                        new { ID = 66, CharTileID = 66, Count = 3, PouchID = 2 },
                        new { ID = 67, CharTileID = 67, Count = 4, PouchID = 2 },
                        new { ID = 68, CharTileID = 68, Count = 4, PouchID = 2 },
                        new { ID = 69, CharTileID = 69, Count = 9, PouchID = 2 },
                        new { ID = 70, CharTileID = 70, Count = 4, PouchID = 2 },
                        new { ID = 71, CharTileID = 71, Count = 4, PouchID = 2 },
                        new { ID = 72, CharTileID = 72, Count = 4, PouchID = 2 },
                        new { ID = 73, CharTileID = 73, Count = 5, PouchID = 2 },
                        new { ID = 74, CharTileID = 74, Count = 3, PouchID = 2 },
                        new { ID = 75, CharTileID = 75, Count = 1, PouchID = 2 },
                        new { ID = 76, CharTileID = 76, Count = 1, PouchID = 2 },
                        new { ID = 77, CharTileID = 77, Count = 1, PouchID = 2 },
                        new { ID = 78, CharTileID = 78, Count = 2, PouchID = 2 },
                        new { ID = 79, CharTileID = 79, Count = 1, PouchID = 2 },
                        new { ID = 80, CharTileID = 80, Count = 1, PouchID = 2 },
                        new { ID = 81, CharTileID = 81, Count = 2, PouchID = 2 },
                        new { ID = 82, CharTileID = 82, Count = 1, PouchID = 2 },
                        new { ID = 83, CharTileID = 83, Count = 1, PouchID = 2 },
                        new { ID = 84, CharTileID = 84, Count = 2, PouchID = 2 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Rack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameID");

                    b.Property<int>("PlayerID");

                    b.Property<int>("PouchID");

                    b.Property<int>("RackSize");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID")
                        .IsUnique();

                    b.HasIndex("PouchID");

                    b.ToTable("Racks");

                    b.HasData(
                        new { ID = 1, GameID = 1, PlayerID = 1, PouchID = 1, RackSize = 7 },
                        new { ID = 2, GameID = 1, PlayerID = 2, PouchID = 1, RackSize = 7 },
                        new { ID = 3, GameID = 1, PlayerID = 3, PouchID = 1, RackSize = 7 },
                        new { ID = 4, GameID = 1, PlayerID = 4, PouchID = 1, RackSize = 7 },
                        new { ID = 5, GameID = 2, PlayerID = 5, PouchID = 2, RackSize = 7 },
                        new { ID = 6, GameID = 2, PlayerID = 6, PouchID = 2, RackSize = 7 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Rack_CharTile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharTileID");

                    b.Property<int>("Count");

                    b.Property<int>("RackID");

                    b.HasKey("ID");

                    b.HasIndex("CharTileID");

                    b.HasIndex("RackID");

                    b.ToTable("Rack_CharTiles");
                });

            modelBuilder.Entity("Scrabble.Models.WordDictionary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameLanguageID");

                    b.HasKey("ID");

                    b.HasIndex("GameLanguageID");

                    b.ToTable("WordDictionaries");

                    b.HasData(
                        new { ID = 1, GameLanguageID = 1 },
                        new { ID = 2, GameLanguageID = 2 }
                    );
                });

            modelBuilder.Entity("Scrabble.Models.Board", b =>
                {
                    b.HasOne("Scrabble.Models.Game", "Game")
                        .WithOne("Board")
                        .HasForeignKey("Scrabble.Models.Board", "GameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.BoardTile", b =>
                {
                    b.HasOne("Scrabble.Models.Board", "Board")
                        .WithMany("BoardTiles")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.BoardTileType", "BoardTileType")
                        .WithMany()
                        .HasForeignKey("BoardTileTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.CharTile", "CharTile")
                        .WithMany()
                        .HasForeignKey("CharTileID");
                });

            modelBuilder.Entity("Scrabble.Models.CharTile", b =>
                {
                    b.HasOne("Scrabble.Models.GameLanguage", "GameLanguage")
                        .WithMany()
                        .HasForeignKey("GameLanguageID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.WordDictionary", "WordDictionary")
                        .WithMany("CharTiles")
                        .HasForeignKey("WordDictionaryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Game", b =>
                {
                    b.HasOne("Scrabble.Models.GameLanguage", "GameLanguage")
                        .WithMany()
                        .HasForeignKey("GameLanguageID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.WordDictionary", "WordDictionary")
                        .WithMany("Games")
                        .HasForeignKey("WordDictionaryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Move", b =>
                {
                    b.HasOne("Scrabble.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Player", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Player", b =>
                {
                    b.HasOne("Scrabble.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Pouch", "Pouch")
                        .WithMany()
                        .HasForeignKey("PouchID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Pouch", b =>
                {
                    b.HasOne("Scrabble.Models.Game", "Game")
                        .WithOne("Pouch")
                        .HasForeignKey("Scrabble.Models.Pouch", "GameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Pouch_CharTile", b =>
                {
                    b.HasOne("Scrabble.Models.CharTile", "CharTile")
                        .WithMany()
                        .HasForeignKey("CharTileID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Pouch", "Pouch")
                        .WithMany("Pouch_CharTiles")
                        .HasForeignKey("PouchID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Rack", b =>
                {
                    b.HasOne("Scrabble.Models.Game", "Game")
                        .WithMany("Racks")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Player", "Player")
                        .WithOne("Rack")
                        .HasForeignKey("Scrabble.Models.Rack", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Pouch", "Pouch")
                        .WithMany()
                        .HasForeignKey("PouchID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.Rack_CharTile", b =>
                {
                    b.HasOne("Scrabble.Models.CharTile", "CharTile")
                        .WithMany()
                        .HasForeignKey("CharTileID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scrabble.Models.Rack", "Rack")
                        .WithMany("Rack_CharTiles")
                        .HasForeignKey("RackID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Scrabble.Models.WordDictionary", b =>
                {
                    b.HasOne("Scrabble.Models.GameLanguage", "GameLanguage")
                        .WithMany()
                        .HasForeignKey("GameLanguageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
